# ---- YOUR APP STARTS HERE ----
# -- Import section --
from flask import Flask, Markup
from flask import render_template
from flask import request
# import model
# -- Initialization section --
app = Flask(__name__)
months = {
    '1990': '1990:' + '<BR><h2>Wrecking cranes began tearing down the Berlin Wall at the Brandenburg Gate (April 29)</h3>' + '<BR><img border="2" width="900" src="https://www.abc.net.au/news/image/9399574-3x2-940x627.jpg"</img>' + '<BR><BR><BR><h2>1,426 pilgrims trampled to death after a panic in a tunnel in Mecca, Saudi Arabia (July 2)</h2>'+ '<BR><img border="2" width="600" src="https://s1.nyt.com/timesmachine/pages/1/1990/07/03/793390_360W.png?quality=75&auto=webp&disable=upscale"</img>' + '<BR><BR><BR><h2>US deploys troops to Saudi Arabia beginning Operation Desert Shield (August 7)</h2>' + '<BR><img border="2" width="900" src="https://archive.defense.gov/dodcmsshare/photoessay/2010-07/hires_DF-ST-91-05287.jpg"' + '<BR><BR><BR><h3> Here are some links for extra information about these three topics:</h3>' + '<BR><p>1. https://www.history.com/this-day-in-history/bush-orders-operation-desert-shield' + '<BR><p>2. https:https://www.history.com/this-day-in-history/pilgrim-stampede-kills-1400' + '<BR><p>3. https://www.history.com/this-day-in-history/bush-orders-operation-desert-shield',
    '1991': '1991:' + '<BR><h2>The formal Prime Minister of India, Ragiv Gandhi, was killed (May 21)</h2>' + '<BR><img border="2" width="600" src="https://cdn.dnaindia.com/sites/default/files/styles/full/public/2020/05/21/906813-rajiv-gandhi-new.jpg"</img>' + '<BR><BR><BR><h2>Gulf War ends after Iraq sets a ceasefire following their retreat to Kuwait (February 28)</h2>' + '<BR><img border="2" width="600" src="https://static.history.state.gov/milestones/desert-storm.jpg"</img>' + '<BR><BR><BR><h2>U.S.S.R comes to a formal end (December 21)</h2>' + '<BR><img border="2" width="600" src="https://image.slidesharecdn.com/thecoldwartheend-140810212935-phpapp02/95/the-cold-war-the-end-1-638.jpg?cb=1407706236"</img>' + '<BR><BR><BR><h3> Here are some links for extra information about these three topics:</h3>' + '<BR><p>1. https://en.wikipedia.org/wiki/Assassination_of_Rajiv_Gandhi' + '<BR><p>2. https://history.state.gov/milestones/1989-1992/gulf-war#:~:text=The%20invasion%20of%20Kuwait%20led,Kuwait%20on%20February%2028%2C%201991.' + '<BR><p>3. https://www.history.com/this-day-in-history/bush-orders-operation-desert-shield',
    '1992': '1992:' + '<BR><h2>John Major elected prime minister of the U.K after his Conservative Party wins the most votes in British electoral history (April 9)</h2>' + '<BR><img border="2"  width="900" src="https://cdn.britannica.com/74/2274-050-7CDD3A91/John-Major-1990.jpg"</img>' + '<BR><h2>The church of New England ordains female priests (November 11)</h2>' + '<BR><img border="2"  width="900" src="https://www.premierchristianity.com/var/ezdemo_site/storage/images/media/images/berner-first-woman/43961341-1-eng-GB/berner-first-woman_article_image.jpg"</img>' +  '<BR><h2>Operation Restore Hope: U.S marines land in Somalia (December 9)</h2>' + '<BR><img border="2"  width="900" src="https://static.politico.com/dims4/default/cae59f1/2147483647/resize/1160x%3E/quality/90/?url=https%3A%2F%2Fstatic.politico.com%2F4e%2F46%2F67f425624a20a0737454fa078a1f%2Fwebp.net-resizeimage%20%2820%29.jpg"</img>',
    '1993': '1993:' + '<BR><h2>Holocaust Memorial Museum dedicated in Washington D.C (April 22)</h2>' + '<BR><img border="2" width="600" src="https://www.ushmm.org/m/img/Kramer_20070423_0829-959.jpg"</img>' + '<BR><h2>Israel and the Palestine Liberation Organization exchange letters of mutual recognition (September 9)</h2>' + '<BR><img border="2" width="600" src="https://www.jewishvirtuallibrary.org/jsource/images/terror/plologo.jpg"</img>' + '<BR><h2>Black and white leaders in South Africa approve new democratic constitution (November 18)</h2>' + '<BR><img border="2" width="900" src="https://www.thefamouspeople.com/profiles/thumbs/desmond-tutu-13.jpg"</img>',
    '1994': '1994:' + '<BR><h2>Nelson Mandela sworn in as South Africas 1st black president (May 10)</h2>' + '<BR><img border="2" width="600" src="https://www.thoughtco.com/thmb/DmpJmdqx7nyvVnNUVkgk1uWca1U=/3000x1687/smart/filters:no_upscale()/GettyImages-805113-5895bb705f9b5874eee58dbd.jpg"</img>' + '<BR><h2>US reopens Guantanamo Naval Base to process refugees (June 29)</h2>' + '<BR><img border="2" width="600" src="https://news.usni.org/wp-content/uploads/2015/07/800px-thumbnail.jpg"</img>' + '<BR><h2>Church of England ordains 1st 33 women priests (March 12)</h2>' + '<BR><img border="2" width="900" src="https://www.economist.com/sites/default/files/20181110_BLP509.jpg"</img>',
    '1995': '1995:' + '<BR><h2>Oklahoma City bombing - a truck bomb at Alfred P. Murrah Federal Building kills 168 & injures 500 (April 19)</h2>' + '<BR><img border="2" width="600" src="https://cbsnews1.cbsistatic.com/hub/i/2020/04/16/780fe8c4-57ed-4d9a-a57c-7f5f5e7788a8/ot-oklahomacityfd-ap.jpg"</img>' + '<BR><h2>7,000 Bosnian Muslim men are massacred when Bosnian Serbs overrun the UN safe haven of Srebrenica (July 11)</h2>' + '<BR><img border="2" width="600" src="https://www.history.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTU3ODc5MDg2NDM3MjQ2Mjgx/a-bosnian-muslim-woman-survivor-of-sreb.jpg"</img>' + '<BR><h2>Comet Hale-Bopp is discovered and becomes visible to the naked eye nearly a year later (July 23)</h2>' + '<BR><img border="2" width="900" src="https://images.immediate.co.uk/production/volatile/sites/25/2020/02/Comet-Hale-Bopp-by-Alan-Hale-10d7d34.jpg?quality=90&resize=620,413"</img>',
    '1996': '1996:' + '<BR><h2>UK House of Commons announces that the Stone of Scone, aka the Stone of Destiny, used in the coronation of Scottish (and subsequently English and British monarchs), will be returned to Scotland after 700 years in Westminster Abbey (July 3)</h2>'+ '<BR><img border="2" width="600" src="https://www.edinburghcastle.scot/media/1140/stone-destiny.jpg?anchor=center&mode=crop&width=1000&height=1000&rnd=132042182210000000"</img>' + '<BR><h2>Osama bin Laden issues message entitled "A declaration of war against the Americans occupying the land of the two holy places" (August 23)</h2>' + '<BR><img border="2" width="900" src="https://www.history.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTU3ODc5MDg2NDMzNTExMTM1/osama-bin-laden-born-march-10-1957-member-of-the-prominent-saudi-bin-laden-family-and-the-founder-of-the-islamic-extremist-organization-al-qaeda-best-known-for-the-september-11-attacks-on-the-unite.jpg"</img>' + '<BR><h2>US President Bill Clinton signs welfare reform into law, representing major shift in welfare policy (August 26)</h2>' + '<BR><img border="2" width="900" src="https://www.biography.com/.image/t_share/MTIwNjA4NjMzNzczOTE3NzA4/bill-clinton-9251236-1-402.jpg"</img>',
    '1997': '1997:' + '<BR><h2>United Kingdom returns Hong Kong and the New Territories to the Peoples Republic of China (July 1)</h2>' + '<BR><img border="2" width="600" src="https://cdn.theatlantic.com/thumbor/GyXk0gnlo08dl9ONZdZJwDSivW8=/76x0:1972x1066/720x405/media/img/mt/2019/07/RTXHFNJ/original.jpg"</img>'+ '<BR><h2>Diana, Princess of Wales, dies in a car crash in a road tunnel in Paris (August 31)</h2>' + '<BR><img border="2"  width="900" src="https://cdn.images.express.co.uk/img/dynamic/106/590x/Princess-Diana-and-crashed-car-840169.jpg"</img>' + '<BR><h2>Google.com is registered as a domain name (September 15)</h2>' + '<BR><img border="2"  width="900" src="https://9to5google.com/wp-content/uploads/sites/4/2017/07/google-2017-07-20-16-57-52.png?w=1600"</img>',
    '1998': '1998:' + '<BR><h2>The Good Friday/Belfast Agreement for Northern Ireland is signed by the British and Irish governments (April 10)</h2>' + '<BR><img border="2" width="600" src="https://ichef.bbci.co.uk/news/410/media/images/65536000/jpg/_65536663_belfastagreement.jpg"</img>' + '<BR><h2>Former Chilean dictator General Augusto Pinochet is arrested in London on a Spanish warrant requesting his extradition on murder charges (October 16)</h2>' + '<BR><img border="2" width="600" src="https://cdn.britannica.com/27/192627-050-522F407B/Pres-Augusto-Pinochet-Chilean-start-military-coup-September-11-1973.jpg"</img>' + '<BR><h2>Hugo Chávez is elected President of Venezuela (December 6)</h2>' + '<BR><img border="2"  width="900" src="https://cdn.britannica.com/68/193768-050-F701AED4/Hugo-Chavez-2010.jpg"</img>',
    '1999': '1999:' + '<BR><h2>US President Bill Clinton acquitted by the Senate in his impeachment trial (February 12)</h2>' + '<BR><img border="2" width="600" src="https://www.thoughtco.com/thmb/DmpJmdqx7nyvVnNUVkgk1uWca1U=/3000x1687/smart/filters:no_upscale()/GettyImages-805113-5895bb705f9b5874eee58dbd.jpg"</img>' + '<Br><h2>The World Trade Organisation rules in favor of the United States in its long-running trade dispute with the European Union over bananas (April 7)</h2>' + '<BR><img border="2" width="900" src="https://www.wto.org/images/slideshow/wto_building/gallery/album/desktop/DSC_8390.jpg"</img>' + '<BR><h2>The Day of Six Billion: the proclaimed 6 billionth living human in the world is born (October 12)</h2>' + '<BR><img border="2" width="900" src="http://news.bbc.co.uk/olmedia/470000/images/_472214_baby300.jpg"</img>',
    '2000': '2000:' + '<BR><h2>Indias population officially reaches 1 billion - Astha Arora named Indias billionth baby (May 11)</h2>' + '<BR><img border="2" width="600" src="https://www.commisceo-global.com/images/easyblog_articles/1901/b2ap3_amp_indian-girls-smiling.jpg"</img>' + '<BR><h2>Controversial US presidential election between George W. Bush and Al Gore is inconclusive; the result, in Bushs favor, is eventually resolved by the Supreme Court (November 7)</h2>' + '<BR><img border="2" width="900" src="https://i.ytimg.com/vi/Odv3oqWIx8g/maxresdefault.jpg"</img>' + '<BR><h2>Microsoft chairman Bill Gates steps aside as chief executive and promotes company president Steve Ballmer to the position (January 13)</h2>' + '<BR><img border="2" width="900" src="https://image.cnbcfm.com/api/v1/image/104891709-Bill_Gates_the_co-Founder.jpg?v=1558120888&w=1400&h=950"</img>',
    '2001': '2001:' + '<BR><h2>US President George W. Bush announces the establishment of the Office of Homeland Security (October 8)</h2>' + '<BR><img border="2"  width="900" src="https://cdn.britannica.com/s:800x450,c:crop/42/172742-138-B0830C03/overview-George-W-Bush.jpg"</img>'+ '<BR><h2>Netherlands becomes the first country in the world to make same-sex marriage legal (April 1)</h2>' + '<BR><img border="2"  width="900" src="https://img.thedailybeast.com/image/upload/c_crop,d_placeholder_euli9k,h_675,w_1200,x_0,y_0/dpr_2.0/c_limit,w_740/fl_lossy,q_auto/v1493049334/articles/2012/05/15/dutch-advice-to-obama-on-same-sex-marriage/gay-marriage-netherlands-devisser_fg1r9b"</img>' + '<BR><h2>Two passenger planes hijacked by Al Qaeda terrorists crash into New Yorks World Trade Towers causing the collapse of both and deaths of 2,606 people (September 11)</h2>' + '<BR><img border="2" width="900" src="https://i.ytimg.com/vi/MNyjZJOEXpE/maxresdefault.jpg"</img>',
    '2002': '2002:' + '<BR><h2>U.S. invasion of Afghanistan: US conventional forces first deployed as part of Operation Anaconda (March 2)</h2>' + '<BR><img border="2"  width="900" src="https://cdn.cfr.org/sites/default/files/styles/slide_cover_m/public/image/2017/05/TL_US_War_Afghanistan.jpg"</img>' + '<BR><h2>The African Union is established in Addis Ababa, Ethiopia. The first chairman is Thabo Mbeki, President of South Africa. (July 9)</h2>' + '<BR><img border="2" width="900" src="https://upload.wikimedia.org/wikipedia/en/thumb/f/f5/Emblem_of_the_African_Union.svg/1200px-Emblem_of_the_African_Union.svg.png"</img>' + '<BR><h2>Enlargement of the European Union: The European Union announces that Cyprus, the Czech Republic, Estonia, Hungary, Latvia, Lithuania, Malta, Poland, Slovakia, and Slovenia will become members from May 1, 2004. (December 13)</h2>' + '<BR><img border="2" width="900" src="https://upload.wikimedia.org/wikipedia/commons/e/ed/Enlargement_of_the_European_Union_77.gif"</img>',
    # '2003': '2003:' + '<BR><h2>Baghdad falls to U.S. forces, ending the Invasion of Iraq, but resulting in widespread looting (April 9)</h2>' + '<BR><img border="2"  width="900" src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/SaddamStatue.jpg/250px-SaddamStatue.jpg"</img>' + '<BR><h2>The Spirit Rover is launched, beginning NASAs Mars Exploration Rover mission (June 10)</h2>' + '<BR><img border="2"  width="900" src="https://cdn.mos.cms.futurecdn.net/EYoiusNmH87rrMTCMaBZbH-320-80.jpg"</img>' + '<BR><h2>Space Shuttle Columbia disintegrates during reentry into the Earth's atmosphere, killing all seven astronauts aboard. (February 1)</h2>' + '<BR><img border="2"  width="900" src="https://cdn.britannica.com/68/193768-050-F701AED4/Hugo-Chavez-2010.jpg"</img>',
    '2004': '2004:',
    '2005': '2005:',
    '2006': '2007:',
    '2009': '2009:',
    '2010': '2010:',
    '2011': '2011:',
    '2012': '2012:',
    '2013': '2013:',
    '2014': '2014:',
    '2015': '2015:',
    '2016': '2016:',
    '2017': '2017:',
    '2018': '2018:',
    '2019': '2019:',
    '2020': '2020:',
}
@app.route('/')
@app.route('/index')
def index():
    return render_template('index.html')
@app.route("/sendMonth", methods=['GET', 'POST'])
def sendMonth():
    sendMonth = request.form['month']
    sendEvent = months[sendMonth]
    print(sendEvent)
    return render_template('results.html', stone=Markup(sendEvent))